#!/bin/bash
#
# Copyright (C) 2022-2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

source ~/.config/dci-pipeline/config


MOUNTED_PATHS=(
  "/var/consoles"
  "${HOME}"
)

# if /var/lib/dic-pipeline is writtable, add it to the mounted paths
if [[ -w /var/lib/dci-pipeline ]]; then
    MOUNTED_PATHS+=("/var/lib/dci-pipeline")
fi

mounts=

for elt in "${MOUNTED_PATHS[@]}" "${CONTAINER_MOUNTED_PATHS[@]}"; do
  if [[ -e "${elt}" ]]; then
    mounts="$mounts -v $elt:$elt"
  fi
done

podman run --rm --security-opt label=disable -e USER -e LC_ALL=C.UTF-8 --userns=keep-id --group-add=wheel --pull=newer $mounts \
       "${DCI_PIPELINE_IMAGE:=quay.io/distributedci/dci-pipeline}":"${DCI_PIPELINE_TAG:=latest}" \
      dci-pipeline "$@"

# dci-pipeline-podman ends here
