#!/bin/bash
#
# Copyright (C) 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

mounts=''
for userfile in $(ls -A $HOME); do
  echo $userfile | grep -Eq '.cache|.local' && continue
  echo $userfile | grep -Eq '.ssh|.netrc' && \
    mounts="$mounts -v ${HOME}/${userfile}:/root/${userfile}:rw" || \
    mounts="$mounts -v ${HOME}/${userfile}:${HOME}/${userfile}:rw"
done

# Consever logs
mounts="$mounts -v /var/consoles/:/var/consoles/:rw"

podman run --rm --security-opt label=disable --privileged --user=root --pull=newer --workdir=${HOME} $mounts \
       "${DCI_PIPELINE_IMAGE:=quay.io/distributedci/dci-pipeline}":"${DCI_PIPELINE_TAG:=latest}" \
       dci-pipeline "$@"

# dci-pipeline-podman ends here
