#!/bin/bash
#
# Copyright (C) 2022 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ -r /etc/dci-openshift-agent/config ]; then
    . /etc/dci-openshift-agent/config
fi

ARGS=''

if [ -n "$CONFIG_DIR" ]; then
    ARGS="$ARGS --mount=type=bind,src=$CONFIG_DIR,dst=$CONFIG_DIR"
fi

mounts=''
for userfile in $(ls -A $HOME); do
  echo $userfile | grep -Eq '.cache|.local' && continue
  mounts="$mounts -v ${HOME}/${userfile}:${HOME}/${userfile}:rw,Z"
done

podman run --rm --userns=keep-id --network=host $mounts $ARGS "${DCI_PIPELINE_IMAGE:=quay.io/distributedci/dci-pipeline}":"${DCI_PIPELINE_TAG:=latest}" dci-openshift-agent-ctl "$@"

# dci-openshift-agent-ctl-podman ends here
