---
  - name: openshift-vanilla
    type: ocp
    location: agents/openshift-vanilla
    outputs: agents/openshift-vanilla/outputs
    topic: OCP-4.4
    components:
      - ocp-4.4
      - ose-tests
      - cnf-tests
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok

  - name: rh-cnf
    type: cnf
    location: agents/rh-cnf
    inputs: agents/rh-cnf/inputs
    topic: RH-CNF-0.1
    components:
      - rh-cnf-0.1
    success_tag: ocp-vanilla-ok
    fallback_last_success: ocp-vanilla-ok
