---
  - name: openshift-vanilla
    type: ocp
    ansible_playbook: agents/openshift-vanilla/agent.yml
    ansible_inventory: agents/openshift-vanilla/inventory
    ansible_extravars:
      answer: 42
    ansible_tags:
      - working
    ansible_skip_tags:
      - broken
    outputs:
      hosts: etc/hosts
    topic: OCP-4.4
    components:
      - ocp=ocp-4.4.0-0.nightly-20200701
      - ose-tests
      - cnf-tests
    success_tag: ocp-vanilla-4.4-ok
    fallback_last_success: ocp-vanilla-4.4-ok

  - name: rh-cnf
    type: cnf
    prev_stages: openshift-vanilla
    ansible_playbook: agents/rh-cnf/agent.yml
    inputs:
      hosts: hosts
    topic: RH-CNF-0.1
    components:
      - rh-cnf
    success_tag: ocp-vanilla-4.4-ok
    fallback_last_success: ocp-vanilla-4.4-ok
