---
  - name: openshift-vanilla
    type: ocp
    configuration: myconf
    url: https://lwn.net/
    ansible_playbook: agents/openshift-vanilla/agent.yml
    ansible_inventory: agents/openshift-vanilla/inventory
    ansible_extravars:
      answer: 42
    ansible_envvars:
      ENVVAR_42: 42
      ENVVAR_43: 43
      ENVVAR_TMPDIR: /@tmpdir
    ansible_tags:
      - working
    outputs:
      hosts: etc/hosts
    topic: OCP-4.4
    components:
      - ocp=ocp-4.4.0-0.nightly-20200701
      - ose-tests
      - cnf-tests
    comment: debugging comment
    success_tag: ocp-vanilla-4.4-simple-ok
    fallback_last_success: ocp-vanilla-4.4-simple-ok

  - name: rh-cnf
    type: cnf
    configuration: myconf
    prev_stages: openshift-vanilla
    ansible_playbook: agents/rh-cnf/agent.yml
    inputs:
      hosts: hosts_path
    ansible_extravars:
      answer: 42
    topic: RH-CNF-0.1
    components:
      - rh-cnf
    success_tag: ocp-vanilla-4.4-simple-ok
    fallback_last_success: ocp-vanilla-4.4-simple-ok
