---
- hosts: testrunner
  tasks:
    - name: Install list of packages
      become: yes
      apt:
        name:
          - docker
          - docker-compose
          - tox
        state: present

    - selinux:
        state: permissive
        policy: targeted
      become: true

    - service:
        name: docker
        state: started
      become: true
