---
- hosts: testrunner
  tasks:
    - name: Install list of packages
      become: yes
      yum:
        name:
          - docker
          - docker-compose
          - tox
        state: present

    - selinux:
        state: permissive
        policy: targeted
      become: yes

    - service:
        name: docker
        state: started
      become: yes

    - name: add user zuul-worker to the docker group
      user:
        name: 'zuul-worker'
        groups: 'docker'
        append: 'yes'
      become: yes
