---
- hosts: testrunner
  vars:
    dcidevenv_path_query: "[?name=='dci-dev-env'].src_dir"
    dcidevenv_path: "{{ (zuul.projects.values() | list | json_query(dcidevenv_path_query))[0] }}"
  tasks:

    - name: build and launch docker images from dci-dev-env
      shell: docker-compose up -d --build api
      environment:
        DCI_GIT_REPO_DIR: ..
      args:
        chdir: '{{ dcidevenv_path }}'

    - name: provision data
      shell: set -x; ./dev-setup/dci-telcoprovisioning
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: run the example pipeline in py27
      shell: set -x; tox -epy27 --notest && . .tox/py27/bin/activate && python dcipipeline/main.py
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: run the example pipeline in py37
      shell: set -x; tox -epy37 --notest && . .tox/py37/bin/activate && python dcipipeline/main.py
      args:
        chdir: "{{ zuul.project.src_dir }}"
