---

- hosts: testrunner
  vars:
    dcidevenv_path_query: "[?name=='dci-dev-env'].src_dir"
    dcidevenv_path: "{{ (zuul.projects.values() | list | json_query(dcidevenv_path_query))[0] }}"
    dciclient_path_query: "[?name=='python-dciclient'].src_dir"
    dciclient_path: "{{ ansible_env.HOME }}/{{ (zuul.projects.values() | list | json_query(dciclient_path_query))[0] }}"
    dciauth_path_query: "[?name=='python-dciauth'].src_dir"
    dciauth_path: "{{ ansible_env.HOME }}/{{ (zuul.projects.values() | list | json_query(dciauth_path_query))[0] }}"
    dciansible_path_query: "[?name=='dci-ansible'].src_dir"
    dciansible_path: "{{ ansible_env.HOME }}/{{ (zuul.projects.values() | list | json_query(dciansible_path_query))[0] }}"
    dcipipeline_path_query: "[?name=='dci-pipeline'].src_dir"
    dcipipeline_path: "{{ ansible_env.HOME }}/{{ (zuul.projects.values() | list | json_query(dcipipeline_path_query))[0] }}"
  tasks:

    - name: Replace DCI_GIT_REPO_DIR in .env file to parent dir
      lineinfile:
        path: "{{ dcidevenv_path }}/.env"
        regexp: '^DCI_GIT_REPO_DIR='
        line: DCI_GIT_REPO_DIR=..

    - name: Remove the ansible packages
      ansible.builtin.package:
        name:
          - ansible
          - ansible-core
        state: absent
      become: true

    - name: Packages for el8
      become: true
      when:
        - ansible_distribution_major_version | int == 8
      block:
        - name: Install EPEL
          ansible.builtin.shell: |
            subscription-manager repos --enable codeready-builder-for-rhel-8-$(arch)-rpms
            dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y

        - name: Install required packages
          ansible.builtin.package:
            name:
              - make
              - podman-compose
              - python3-tox
              - git

    - name: Build and launch the control server container images from dci-dev-env
      shell: |
        set -ex
        sudo modprobe iptable-nat
        podman-compose build db api
        podman-compose up -d db api
      args:
        chdir: '{{ dcidevenv_path }}'

    - name: Check podman-compose status
      shell: |
        set -ex
        podman-compose ps
        podman-compose logs db
        podman-compose logs api
        if [ "$(podman ps -a -f status=exited --format json)" != '[]' ]; then
           exit 1
        fi
      args:
        chdir: '{{ dcidevenv_path }}'
        executable: "/bin/bash"

    - name: Provision data
      command: ./dev-setup/dci-telcoprovisioning
      args:
        chdir: "{{ dcipipeline_path }}"

    - name: Force requirements for el8
      ansible.builtin.copy:
        src: "{{ dcipipeline_path }}/requirements.txt.el8"
        dest: "{{ dcipipeline_path }}/requirements.txt"
        mode: "0644"
        remote_src: true
      when: ansible_distribution_major_version | int == 8

    - name: Force to use dciclient from the local copy
      ansible.builtin.replace:
        path: "{{ dcipipeline_path }}/requirements.txt"
        regexp: '^dciclient$'
        replace: '-e {{ dciclient_path }}'

    - name: Force to use dciauth from the local copy
      ansible.builtin.replace:
        path: "{{ dcipipeline_path }}/requirements.txt"
        regexp: '^dciauth$'
        replace: '-e {{ dciauth_path }}'

    - name: Install python dependencies via tox
      command: tox -efunctional --notest
      args:
        chdir: "{{ dcipipeline_path }}"

    - name: Install Ansible dependencies
      shell: |
        set -ex
        . .tox/functional/bin/activate
        [ $(type -p ansible-playbook) != /usr/bin/ansible-playbook ]
        ./container/install-from-source.sh
      environment:
        ANSIBLE_ROLES_PATH: "~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
        ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections:/usr/share/ansible/collections"
        ANSIBLE_DIR: "~/.ansible/roles"
      args:
        chdir: "{{ dcipipeline_path }}"

    - name: Run the example pipelines in Python 3
      shell: |
        set -ex
        env|grep ANSIBLE
        tox
      environment:
        ANSIBLE_lIBRARY: "{{ dciansible_path }}"
        ANSIBLE_COLLECTIONS_PATHS: "~/.ansible/collections:/usr/share/ansible/collections"
        ANSIBLE_ROLES_PATH: "~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
      args:
        chdir: "{{ dcipipeline_path }}"

...
