---
- name: Schedule a job
  hosts: runner
  gather_facts: false
  tags:
    - working
    - init
  tasks:

    - name: Read credentials from env vars
      set_fact:
        dci_client_id: "{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret: "{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url: "{{ lookup('env','DCI_CS_URL') }}"
        dci_ui_url: "{{ lookup('env','DCI_UI_URL') }}"
        envvar_42: "{{ lookup('env','ENVVAR_42') }}"
        envvar_43: "{{ lookup('env','ENVVAR_43') }}"
      no_log: true

    - name: validate environment variables
      assert:
        that:
          - envvar_42 == "42"
          - envvar_43 == "43"

    - name: stat the tmpdir environment variable
      stat:
        path: "{{ lookup('env','ENVVAR_TMPDIR') }}"
      register: tmpdir

    - name: check the existence of the temporary directory
      assert:
        that:
          - tmpdir.stat.exists

    - name: Schedule a new job
      dci_job:
        topic: '{{ dci_topic }}'
      register: job_info
      when: job_info is not defined

    - name: Print job_info
      debug:
        msg: "{{ job_info['job'] }}"

    - name: Set global variables
      set_fact:
        job_id: "{{ job_info['job']['id'] }}"
        topic_id: "{{ job_info['job']['topic_id'] }}"
        remoteci_id: "{{ job_info['job']['remoteci_id'] }}"
        components: "{{ job_info['job']['components'] }}"
        product: "{{ job_info['job']['topic']['product_id'] }}"

    - name: set job state
      dci_job:
        id: "{{ job_id }}"
        status: "new"

    - name: Print job id
      debug:
        msg: "dci_job_id: {{ job_id }}"

    - name: Print components
      debug:
        msg: "{{ item }}"
      with_items: "{{ job_info['job']['components'] }}"

    - name: 'Set tags for the current job'
      dci_job:
        id: "{{ job_id }}"
        tags: 'ocp-vanilla-conf'

- name: Preparation tasks
  hosts: runner
  gather_facts: false
  tags:
    - working
  tasks:

    - name: pre-run
      dci_job:
        id: "{{ job_id }}"
        status: "pre-run"

    - name: get status
      dci_job:
        id: "{{ job_id }}"
      register: dci_status

    - name: validate status
      assert:
        that:
          - dci_status.job.status == "pre-run"

    - name: get OCP version from job_info
      set_fact:
        ocp_version: "{{ item.name }}"
      with_items: "{{ job_info.job.components }}"
      when: item["type"] == "ocp"

    - name: do some checks
      assert:
        success_msg: "All components are present and ocp_version is defined"
        fail_msg: "There are missing components or ocp_version cannot be found"
        that:
          - "components|length == 3"
          - ocp_version is defined

    - name: display ocp_version
      debug:
        msg: "OCP version {{ ocp_version }}"

    - name: validate extravars
      assert:
        that:
          - "answer == 42"

- name: Running ocp deployment
  hosts: runner
  gather_facts: false
  tags:
    - working
  tasks:
    - name: running
      dci_job:
        id: "{{ job_id }}"
        status: "running"

    - name: install ocp
      shell: echo 'installing some ocp here'

- name: Rescue construct
  hosts: runner
  gather_facts: false
  tags:
    - working
  tasks:
    - block:
        - name: Broken task to rescue
          fail:
            msg: "broken task"
      rescue:
        - name: get status
          dci_job:
            id: "{{ job_id }}"
          register: dci_status

        - name: validate status
          assert:
            that:
              - dci_status.job.status == "running"

- name: Post-run tasks
  hosts: runner
  gather_facts: false
  tags:
    - working
  tasks:
    - name: post-run
      dci_job:
        id: "{{ job_id }}"
        status: "post-run"

    - name: Print job outputs location
      debug:
        msg: "{{ job_info['outputs'] }}"

    - name: Copy /etc/hosts file to the outputs location
      fetch:
        flat: true
        src: "/etc/hosts"
        dest: "{{ job_info['outputs']['hosts'] }}"

- name: Success tasks
  hosts: runner
  gather_facts: false
  tags:
    - working
  tasks:
    - name: success
      dci_job:
        id: "{{ job_id }}"
        status: "success"

    - name: success message
      debug:
        msg: >
          'The job is now finished.
          Review the log at:
          {{ dci_ui_url|default("https://www.distributed-ci.io")
          }}/jobs/{{ hostvars.localhost.job_info.job.id }}/jobStates'
