#!/bin/bash
#
# Copyright (C) 2023-2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -x

TOPDIR=$(cd "$(dirname "$0")" || exit; pwd)

if [[ $0 =~ .*-podman$ ]]; then
    SUFFIX=-podman
else
    SUFFIX=
fi

if [ -r "$TOPDIR/common$SUFFIX" ]; then
    BASEDIR="$TOPDIR"
else
    BASEDIR=/usr/share/dci-pipeline
fi

source "$BASEDIR/common$SUFFIX"
REPO=${1/*\/}
shift

# Send alerts to Slack
if [[ ${#SLACK_ALERT_WEBHOOKS[@]} -gt 0 ]]; then
    # send alerts only if a webhook is defined for the repo in SLACK_ALERT_WEBHOOKS
    if [[ -n "${SLACK_ALERT_WEBHOOKS[${REPO}]}" ]]; then
        data='{"blocks": [{"type": "section","text": {"text": "'"${*}"'", "type": "mrkdwn"}}]}'
        curl -sL \
        -H "Content-Type: application/json; charset=UTF-8" \
        --data "${data}" \
        "${SLACK_ALERT_WEBHOOKS[${REPO}]}"
    fi
fi
