#!/bin/bash
#
# Copyright (C) 2022-2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

TOPDIR=$(cd $(dirname $0); pwd)

if [[ $0 =~ .*-podman$ ]]; then
    SUFFIX=-podman
else
    SUFFIX=
fi

if [ -r "$TOPDIR/common$SUFFIX" ]; then
    BASEDIR="$TOPDIR"
else
    BASEDIR=/usr/share/dci-pipeline
fi

. "$BASEDIR/common$SUFFIX"
DCI_QUEUE="$DEFAULT_QUEUE"

# get an optional dci-queue pool name with -p
if [ "$1" = "-p" ]; then
    shift
    DCI_QUEUE="$1"
    shift
fi

# get an optional dci-queue resource name with -r
if [ "$1" = "-r" ]; then
    shift
    export DCI_QUEUE_RESOURCE="$1"
    shift
fi

if [ -n "$DCI_QUEUE_RESOURCE" ]; then
    RES="$DCI_QUEUE_RESOURCE"
else
    RES="@RESOURCE"
fi

# set PATH for yaml2json
PATH=$BASEDIR:$PATH

CMD=
OPTS=

# separate the dci-queue options from the dci-pipeline ones
for arg in "$@"; do
    case "$arg" in
        -*)
            OPTS="$OPTS $arg"
            ;;
        *)
            CMD="$CMD $arg"
            ;;
    esac
done

if [ -z "$DCI_QUEUE" ] || [ -n "$DCI_QUEUE_RESOURCE" ]; then
    CMD="env DCI_QUEUE=$DCI_QUEUE RES=$RES $BASEDIR/dci-pipeline-helper$SUFFIX $CMD"
else
    CMD="dci-queue schedule $OPTS $DCI_QUEUE env DCI_QUEUE=$DCI_QUEUE RES=$RES $BASEDIR/dci-pipeline-helper$SUFFIX $CMD"
fi

echo "+ $CMD" 1>&2

exec $CMD

# dci-pipeline-schedule ends here
