#!/bin/bash
#
# Copyright (C) 2020 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -x

DCI_QUEUE=${DCI_QUEUE:=8nodes}

if [ $# -lt 2 ]; then
    echo "Usage: $0 [-r] <dci queue resource> <schedule args...>" 1>&2
    exit 1
fi

if [ "$1" = "-r" ]; then
    REMOVE=1
    shift
fi

export DCI_QUEUE_RESOURCE="$1"
shift

try=1
while "$@"; do
    try=$(($try + 1))
    echo "Launching try no $try"
done

if [ "$REMOVE" = 1 ]; then
    dci-queue remove-resource $DCI_QUEUE $DCI_QUEUE_RESOURCE
fi

# loop_until_failure ends here
